package com.app.hotelalura.components;

import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Dimension;

import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Popup;
import javax.swing.PopupFactory;
import javax.swing.text.html.Option;
import java.awt.GridLayout;
import java.awt.BorderLayout;
import java.awt.GridBagLayout;
import java.awt.FlowLayout;

public class TestNewComp extends javax.swing.JFrame {

    /**
     * Esta es una alternativa que estaba probando para
     * reemplazar AbsoluteLayout que me da error al empaquetar
     * aun no encuentro la informacion necesaria para entender porque
     * ocurre el error de que no encuentra el ClassPath de ese jar,
     * Per en todo caso puedo usar Layared panels, con este puede usar
     * el posicionamiento por eje z , tambien me servira en sustituir al loginView
     * que
     * es un frame , pero no queda del todo bien usar otro frame para eso.
     * En todo caso lo dejo aqui para cuando quiera refactorizar ya tenga un ejemplo
     * con lo que estaba practicando.
     */
    public TestNewComp() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        loginForm = new LoginForm(null);
        roundedPanel1 = new com.app.hotelalura.components.RoundedPanel();
        ImgRoundCorner = new ImgRoundCorner();
        JLayeredPane laJLayeredPane = new JLayeredPane();
        JButton btn= new JButton("dsadsadsd");
        JButton btn2= new JButton("dsadsadsd");

        ImgRoundCorner.setIcon(new ImageIcon(getClass().getResource("/images/menu-img.png")));
        ImgRoundCorner.setBackground(Color.red);
        JPanel p2 = new JPanel();
        p2.setLayout(new FlowLayout());
        p2.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        p2.setBackground(Color.red);
        p2.setPreferredSize(new Dimension(300, 520));
        p2.add(btn);
        p2.add(btn2);
        ImgRoundCorner.setPreferredSize(new Dimension((int) (1024 - p2.getPreferredSize().getWidth()), 520));

        JPanel footer = new JPanel();
        footer.setBackground(Color.DARK_GRAY);
        footer.setPreferredSize(new Dimension(1024,80));

        
        JPanel p3= new JPanel();
        p3.setBackground(new Color(0, 0, 0, 80));
        p3.setBounds(0,0,1024, 598);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setBackground(new java.awt.Color(255, 255, 255, 0));
        setPreferredSize(new Dimension(1024, 600));

        laJLayeredPane.setPreferredSize(new Dimension((int) getPreferredSize()
                .getWidth(), (int) getPreferredSize().getHeight()));
        roundedPanel1.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel1.setBounds(0, 0, (int) laJLayeredPane.getPreferredSize().getWidth(),
                (int) laJLayeredPane.getPreferredSize().getHeight());
        roundedPanel1.setLayout(new BorderLayout());
        roundedPanel1.add(ImgRoundCorner, BorderLayout.WEST);
        roundedPanel1.add(p2, BorderLayout.EAST);
        roundedPanel1.add(footer,BorderLayout.SOUTH);

        laJLayeredPane.add(roundedPanel1, JLayeredPane.DEFAULT_LAYER);
        p3.setVisible(false);
        laJLayeredPane.add(p3,Integer.valueOf(1));

        add(laJLayeredPane);

        
        

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new TestNewComp().setVisible(true));

    }

    private ImgRoundCorner ImgRoundCorner;
    private com.app.hotelalura.components.LoginForm loginForm;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.app.hotelalura.components.RoundedPanel roundedPanel1;
    // End of variables declaration//GEN-END:variables
}
